packages:
  - 'packages/extensions/*'
  - 'packages/shell'
  - 'packages/ui'
  - 'packages/sclsdk'
  - 'packages/fileio'
catalog:
  '@septkit/fileio': 0.0.3
  '@septkit/ui': 0.0.6
  dexie: ^4.2.0

linkWorkspacePackages: true
sharedWorkspaceLockfile: false
autoInstallPeers: true
