packages:
  - 'packages/extensions/*'
  - 'packages/shell'
  - 'packages/ui'
  - 'packages/sclsdk'
  - 'packages/fileio'

linkWorkspacePackages: true
sharedWorkspaceLockfile: false
autoInstallPeers: true
