packages:
  - 'packages/extensions/*'
  - 'packages/shell'
  - 'packages/ui'
  - 'packages/sclsdk'
  - 'packages/fileio'
catalog:
  '@septkit/fileio': 0.0.4
  '@septkit/ui': 0.0.7
  dexie: ^4.2.0

linkWorkspacePackages: false
sharedWorkspaceLockfile: false
autoInstallPeers: true
