import { type Node } from '@vue-flow/core'

export const initialNodes: Node[] = [
	{
		id: '1',
		type: 'bay',
		draggable: false,
		data: { label: 'TEMPLATE' },
		position: { x: 0, y: 0 },
		class: 'light',
	},
	{
		id: '2',
		type: 'bay',
		draggable: false,
		data: { label: 'TEMPLATE' },
		position: { x: 0, y: 0 },
		class: 'light',
		parentNode: '1',
		extent: 'parent',
	},
	{
		id: '3',
		type: 'bay',
		draggable: false,
		data: { label: 'TEMPLATE' },
		position: { x: 0, y: 0 },
		class: 'light',
		parentNode: '2',
		extent: 'parent',
	},
	{
		id: '4',
		type: 'bay',
		draggable: false,
		data: { label: 'PROT interface' },
		position: { x: 0, y: 0 },
		class: 'light',
		parentNode: '3',
		extent: 'parent',
	},
	{
		id: '5',
		type: 'bay',
		draggable: false,
		data: { label: 'Output Conditioner' },
		position: { x: 0, y: 0 },
		class: 'light',
		parentNode: '3',
		extent: 'parent',
	},
	{
		id: '6',
		type: 'bay',
		draggable: false,
		data: { label: 'Binary Output' },
		position: { x: 0, y: 0 },
		class: 'light',
		parentNode: '3',
		extent: 'parent',
	},
]

export const initialEdges = [
	// {
	// 	id: 'e1-2',
	// 	source: '1',
	// 	target: '2',
	// 	animated: true,
	// },
	// {
	// 	id: 'e1-3',
	// 	source: '1',
	// 	target: '3',
	// 	label: 'edge with arrowhead',
	// 	markerEnd: MarkerType.ArrowClosed,
	// },
	// {
	// 	id: 'e4-5',
	// 	type: 'step',
	// 	source: '4',
	// 	target: '5',
	// 	label: 'Node 2',
	// 	style: { stroke: 'orange' },
	// 	labelBgStyle: { fill: 'orange' },
	// },
	// {
	// 	id: 'e3-4',
	// 	type: 'smoothstep',
	// 	source: '3',
	// 	target: '4',
	// 	label: 'smoothstep-edge',
	// },
]
