name: Check Package Changes and Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            packages/**

      - name: Count unique changed package and extension folders
        id: count-changed
        run: |
          files="${{ steps.changed-files.outputs.all_changed_files }}"
          folders=$(echo "$files" | tr ' ' '\n' | grep -E '^packages/[^/]+/|^packages/extensions/[^/]+/' | sed -E 's@^(packages/[^/]+).*@\1@;s@^(packages/extensions/[^/]+).*@\1@' | sort | uniq)
          count=$(echo "$folders" | wc -l)
          echo "unique_folders=$count" >> $GITHUB_OUTPUT

      - name: Add or update comment if multiple packages or extensions changed
        if: steps.count-changed.outputs.unique_folders != '0' && steps.count-changed.outputs.unique_folders != '1'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: Changes detected in **multiple** packages or extensions!
            Please consider to split up your changes into separate PRs, each focusing on a single package or extension.
            Beware that if the packages and their unpublished versions are dependent on each other, the build, test and deployment might fail.
          comment-id: package-change-checklist
          edit-mode: replace

      - name: Delete comment if only one or zero folders changed
        if: steps.count-changed.outputs.unique_folders == '0' || steps.count-changed.outputs.unique_folders == '1'
        uses: peter-evans/delete-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: package-change-checklist
