name: Test @septkit/ui

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/ui/**'

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/_install.yml
    with:
      package-name: ui

  test:
    name: Run Tests
    needs: install
    uses: ./.github/workflows/_test.yml
    with:
      package-name: ui

  lint:
    name: Lint Code
    needs: install
    uses: ./.github/workflows/_lint.yml
    with:
      package-name: ui
